<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYAOLgTP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYAOLgTP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYAOLgTP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYAOLgTP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYAOLgTP\App_KernelDevDebugContainer([
    'container.build_hash' => 'YAOLgTP',
    'container.build_id' => 'db775700',
    'container.build_time' => 1762973097,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYAOLgTP');
