<?php

namespace ContainerYAOLgTP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConversationControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ConversationController' shared autowired service.
     *
     * @return \App\Controller\ConversationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ConversationController.php';

        $container->services['App\\Controller\\ConversationController'] = $instance = new \App\Controller\ConversationController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\ConversationRepository'] ?? $container->load('getConversationRepositoryService')), ($container->privates['App\\Repository\\MessageRepository'] ?? $container->load('getMessageRepositoryService')), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->privates['debug.serializer'] ?? self::getDebug_SerializerService($container)));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\ConversationController', $container));

        return $instance;
    }
}
